import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { part1, part2 } from './day06.js';

describe('Day 06', () => {
    it('part 1 - sample input', () => {
        const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;
        assert.equal(part1(input), 41);
    });

    it('part 2 - sample input', () => {
        const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;
        assert.equal(part2(input), 6);
    });
}); 